spring:
  thymeleaf:
    cache: false
    mode: HTML
    check-template: false
    enabled: true
  application:
    name: WEB-SITE
  devtools:
    add-properties: true
  profiles:
    active: prod
server:
  port: 7777